targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          include_if_null: false
      riverpod_generator:
        options:
          generate_providers: true
      retrofit_generator:
        options:
          generate_to_json: true
